name: 'Grid.ai Stop Run'
on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
      run_time:
        required: true
        type: int
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - run: |
          export run_status=$(grid status ${{ github.event.inputs.run_name }} | grep ${{ github.event.inputs.run_name }} | awk '{print $6}')
          echo "run_status=${run_status}" >> $GITHUB_ENV   
          export run_duration=$(grid status ${{ github.event.inputs.run_name }} | grep ${{ github.event.inputs.run_name }} | awk '{print $10}'| cut -d 'd' -f 1)   
          echo "run_duration=${run_duration}" >> $GITHUB_ENV
          export run_name=${{ github.event.inputs.run_name }}
          echo "$run_name"
          echo Runstatus "${run_status}"
          echo RunDuration "${run_duration}
      - run: |
          echo Runstatus "${run_status}"
          echo RunDuration "${run_duration}"

