name: 'Grid.ai Terminate Run'
on:
  workflow_dispatch:
    inputs:
      run_name:
        required: false
        default:  "c$(date '+%y%m%d-%H%M%S')"
        type: string
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - run: |
          echo The RunName is ${{ github.event.inputs.run_name }}
          echo EXP_NAME= "${{ github.event.inputs.run_name }}-exp0"           
      - run: |
          export RUN_STATUS=$(grid status ${{ github.event.inputs.run_name }} |  awk -F, '{print $3}')
          echo Run status : ${RUN_STATUS}
          grid status ${{ github.event.inputs.run_name }}
      - id: grid-status
        uses: gridai-actions/gridai-status@v0
        with:
          obj-type: run
          obj-id: ${run_name}
