name: 'Grid.ai Terminate Run'
on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
      run_time:
        required: true
        type: int
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - run: |
          echo The RunName is ${{ github.event.inputs.run_name }}
          echo EXP_NAME= "${{ github.event.inputs.run_name }}-exp0"           
      - run: |
          export RUN_STATUS=$(grid status ${{ github.event.inputs.run_name }} | grep ${{ github.event.inputs.run_name }} | awk '{print $6}')
          echo "Runstatus=${RUN_STATUS}" >> $GITHUB_ENV
          export RUN_TIME=$(grid status ${{ github.event.inputs.run_name }} | grep c${{ github.event.inputs.run_name }} | awk '{print $10}'| cut -d 'd' -f 1)
          echo "RunTime=${RUN_TIME}" >> $GITHUB_ENV
          while [ "${RUN_STATUS}" = 'running' ]; do
           if [[ "${{ github.event.inputs.run_time }}" >= "${RUN_TIME}"]]; then
               grid stop ${{ github.event.inputs.run_name }}
          fi
          done  
      - id: grid-status
        uses: gridai-actions/gridai-status@v0
        with:
          obj-type: run
          obj-id: ${run_name}
