name: 'Grid.ai Stop Run'
on:
 # schedule:
    # Runs "at 10pm" (see https://crontab.guru)
   # - cron: '*/2 * * * *'
jobs:
  gridai-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - run: |
          export RUN_STATUS_T1=$(grid status ${{ secrets.RUN_NAME }})
          echo $RUN_STATUS_T1
          export RUN_STATUS_T2=$(grid status ${{ secrets.RUN_NAME }} | grep ${{ secrets.RUN_NAME }})
          echo $RUN_STATUS_T2
          export RUN_STATUS=$(grid status ${{ secrets.RUN_NAME }} | grep ${{ secrets.RUN_NAME }} | awk '{print $6}')
          # 1 mins interval
          export "RUN_STATUS=${RUN_STATUS} >> $GITHUB_ENV
          export RUN_DURATION=$(grid status ${{ secrets.RUN_NAME }} | grep ${{ secrets.RUN_NAME }} | awk '{print $10}'| cut -d 'd' -f 1)   
          echo "RUN_DURATION=${RUN_DURATION}" >> $GITHUB_ENV       
      - name: delete-long-running-run
        run: |
          case $RUN_STATUS in 
            running)
              echo "${{ secrets.RUN_NAME }} is running" 
              ;;
            *)
              echo "${{ secrets.RUN_NAME }} is not running"
              exit 1
          esac  
          if [[ "${RUN_DURATION}" > "${{ secrets.RUN_DURATION }}" ]]; then
            echo "Run duration has exceeded ${RUN_DURATION} ${{ secrets.RUN_NAME }} is being stopped"
            grid run stop ${{ secrets.RUN_NAME }}
          fi
