name: 'Grid.ai Terminate Run'
on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
      run_time:
        required: true
        type: int
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
        env:
          RUN_STATUS: temp
          RUN_DURATION: 0
      - run: |
          export ${{ env.RUN_STATUS }}=$(grid status ${{ github.event.inputs.run_name }} | grep ${{ github.event.inputs.run_name }} | awk '{print $6}')
          echo "Runstatus ${{ env.RUN_STATUS }}" >> $GITHUB_ENV
          export ${{ env.RUN_DURATION }} = $(grid status ${{ github.event.inputs.run_name }} | grep ${{ github.event.inputs.run_name }} | awk '{print $10}'| cut -d 'd' -f 1)
          echo "RunTime ${{ env.RUN_DURATION }}" >> $GITHUB_ENV
          while [ ${{ env.RUN_STATUS }} = running ]; do
           if [[ "${{ github.event.inputs.run_time }}" = "$RUN_TIME"]]; then
               grid stop ${{ github.event.inputs.run_name }}
          fi
          done  
      - id: grid-status
        uses: gridai-actions/gridai-status@v0
        with:
          obj-type: run
          obj-id: ${run_name}
