name: 'Grid.ai Stop Run'
on:
  schedule:
    # Runs "at 10pm" (see https://crontab.guru)
    - cron: '55 * * * *'
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - run: |
          export RUN_STATUS=$(grid status ${{ secrets.RUN_NAME }} | grep ${{ secrets.RUN_NAME }} | awk '{print $6}')
          # 1 mins interval
          export run_status=$RUN_STATUS
          export RUN_DURATION=$(grid status ${{ secrets.RUN_NAME }} | grep ${{ secrets.RUN_NAME }} | awk '{print $10}'| cut -d 'd' -f 1)   
          echo "run_duration=$RUN_DURATION" >> $GITHUB_ENV
          export run_name=${{ secrets.RUN_NAME }}
          echo "$run_name"
          echo "$run_status"
          echo "$run_duration"         
      - name: delete-long-running-run
        run: |
          case $RUN_STATUS in 
            cancelled)
              echo "${{ github.event.inputs.run_name }} is stopped" 
              ;;
            *)
              echo "${{ github.event.inputs.run_name }} is not running"
              exit 1
          esac  
          if [[ "${run_duration}" > "${{ secrets.RUN_DURATION }}" ]]; then
            echo "Run duration has exceeded ${RUN_DURATION} ${{ secrets.RUN_NAME }} is being stopped"
            grid run stop ${{ github.event.inputs.run_name }}
          fi
