name: 'Grid.ai Stop Run'
on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
      run_time:
        required: true
        type: int
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - run: |
          export run_status=$(grid status ${{ github.event.inputs.run_name }} | grep ${{ github.event.inputs.run_name }} | awk '{print $6}')
          echo "run_status=${run_status}" >> $GITHUB_ENV   
          export run_duration=$(grid status ${{ github.event.inputs.run_name }} | grep ${{ github.event.inputs.run_name }} | awk '{print $10}'| cut -d 'd' -f 1)   
          echo "run_duration=${run_duration}" >> $GITHUB_ENV
          export run_name=${{ github.event.inputs.run_name }}
          echo "$run_name"
          echo Runstatus "${run_status}"
          echo RunDuration "${run_duration}"         
      - name: delete-long-running-run
        run: |
          case ${RUN_STATUS} in
            running)
              ;;
            *)
              echo "${{ github.event.inputs.run_name }} is not running"
              exit 1
          esac  
          if [[ "${RUN_DURATION}" > "$${{ github.event.inputs.run_time }}" ]]; then
            echo "Run duration has exceeded crossed threhold: ${RUN_DURATION} Run is being deleted"
            grid run stop run cordial-shirley-3622
          fi
      - run: |
          echo Runstatus "${run_status}"
          echo RunDuration "${run_duration}"

