name: 'Grid.ai Terminate Run'
on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        default:  "c$(date '+%y%m%d-%H%M%S')"
        type: string
      run_time:
        required: true
        type: int
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - run: |
          echo The RunName is ${{ github.event.inputs.run_name }}
          echo EXP_NAME= "${{ github.event.inputs.run_name }}-exp0"           
      - run: |
          export RUN_STATUS=$(grid status cordial-shirley-3622 | grep cordial-shirley-3622 | awk '{print $6}')
          echo "Run status : ${RUN_STATUS}"
          export RUN_TIME=$(grid status cordial-shirley-3622 | grep cordial-shirley-3622 | awk '{print $10}'| cut -d 'd' -f 1)
          echo "Run Time : ${RUN_TIME}"
          while [ "${RUN_STATUS}" = 'running' ]; do
           if [[ "${RUN_TIME}" lt "$${{ github.event.inputs.run_time }}" ]]; then
            echo "Error: ${ RUN_TIME } is less then "$${{ github.event.inputs.run_time }}""
          fi
          done
          case ${RUN_STATUS} in
            running)
              ;;
            *)
              echo "${RUN_NAME} is not running"
              exit 1
          esac  
          
          
      - id: grid-status
        uses: gridai-actions/gridai-status@v0
        with:
          obj-type: run
          obj-id: ${run_name}
